language: node_js
node_js:
  - "6"
  - "8"
  - "10"
  - "11"
script:
  - yarn format
  - yarn lint
  - yarn test --coverage
after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
