language: node_js
node_js:
  - "8"
  - "10"
  - "12"
  - "13"
script:
  - yarn format
  - yarn lint
  - yarn test --coverage
  - yarn check-git
after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
