language: node_js
node_js:
  - "10"
  - "12"
  - "13"
  - "14"
branches:
  only:
    - master
script:
  - yarn install --pure-lockfile
  - yarn format
  - yarn lint
  - yarn test --coverage
  - yarn check-git
after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
