- action:
    name: put_config
    data:
      cors: "*"
      headers:
        hfoo: "hfoo"
        hbar: "hbar"
      query:
        qfoo: "qfoo"
        qbar: "qbar"
      cookies:
        cfoo: "cfoo"
        cbar: "cbar"
  expectation:
    status: 200
    bodyJSON:
      cors: "*"
      headers:
        hfoo: "hfoo"
        hbar: "hbar"
      query:
        qfoo: "qfoo"
        qbar: "qbar"
      cookies:
        cfoo: "cfoo"
        cbar: "cbar"
- action:
    name: get_config
  expectation:
    status: 200
    bodyJSON:
      cors: "*"
      headers:
        hfoo: "hfoo"
        hbar: "hbar"
      query:
        qfoo: "qfoo"
        qbar: "qbar"
      cookies:
        cfoo: "cfoo"
        cbar: "cbar"
