- action:
    name: put_config
    data:
      cors: null
  expectation:
    status: 200
    bodyJSON:
      cors: null
      headers: {}
      query: {}
      cookies: {}
- action:
    name: put_config
    data: {}
  expectation:
    status: 200
    bodyJSON:
      cors: null
      headers: {}
      query: {}
      cookies: {}
- action:
    name: put_config
    data:
      cors: null
  expectation:
    status: 200
    bodyJSON:
      cors: null
      headers: {}
      query: {}
      cookies: {}
