- action:
    name: put_config
    data:
      cors: "*"
      headers:
        hfoo:
          hfoo: "hfoo"
        hbar:
          hbar: "hbar"
      query:
        qfoo:
          qfoo: "qfoo"
        qbar:
          qbar: "qbar"
      cookies:
        cfoo:
          cfoo: "cfoo"
        cbar:
          cbar: "cbar"
  expectation:
    status: 200
    bodyJSON:
      cors: "*"
      headers:
        hfoo:
          hfoo: "hfoo"
        hbar:
          hbar: "hbar"
      query:
        qfoo:
          qfoo: "qfoo"
        qbar:
          qbar: "qbar"
      cookies:
        cfoo:
          cfoo: "cfoo"
        cbar:
          cbar: "cbar"
- action:
    name: get_config
  expectation:
    status: 200
    bodyJSON:
      cors: "*"
      headers:
        hfoo:
          hfoo: "hfoo"
        hbar:
          hbar: "hbar"
      query:
        qfoo:
          qfoo: "qfoo"
        qbar:
          qbar: "qbar"
      cookies:
        cfoo:
          cfoo: "cfoo"
        cbar:
          cbar: "cbar"
