- action:
    name: put_config
    data:
      cookies:
        jwt:
          jwt: "jwt"
  expectation:
    status: 200
    bodyJSON:
      cors: null
      headers: {}
      query: {}
      cookies:
        jwt:
          jwt: "jwt"
- action:
    name: put_config
    data:
      cookies:
        jwt2:
          jwt2: "jwt2"
        jwt3:
          jwt3: "jwt3"
  expectation:
    status: 200
    bodyJSON:
      cors: null
      headers: {}
      query: {}
      cookies:
        jwt:
          jwt: "jwt"
        jwt2:
          jwt2: "jwt2"
        jwt3:
          jwt3: "jwt3"
