name: CI
on: [push]
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [20, 22]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'
      - run: yarn install
      - run: yarn format
      - run: yarn lint
      - run: yarn build
      - run: yarn test:bin
      - run: yarn test --coverage
      - run: yarn check-git
      - run: chmod -R 777 ./coverage
      - uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
